### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Norelec91** [gsathya/SDL-emscripten#13]
Hi,
I've followed this tutorial http://gsathya.in/blog/mozilla/sdl2-emscripten.html to build SDL2 on emscripten but I can't.
I'm using Linux Mint Debian Edition and here is log:

alessandro@alessandro ~/SDL-emscripten $ emmake make
Warning, configure.in is out of date
# (cd /home/alessandro/SDL-emscripten && sh autogen.sh && sh configure)

/bin/bash build-scripts/mkinstalldirs build
mkdir -p -- build
/bin/bash build-scripts/updaterev.sh
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL.lo -c /home/alessandro/SDL-emscripten/src/SDL.c -o build/SDL.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL.lo -c /home/alessandro/SDL-emscripten/src/SDL.c -o build/SDL.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_assert.lo -c /home/alessandro/SDL-emscripten/src/SDL_assert.c -o build/SDL_assert.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_assert.lo -c /home/alessandro/SDL-emscripten/src/SDL_assert.c -o build/SDL_assert.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_error.lo -c /home/alessandro/SDL-emscripten/src/SDL_error.c -o build/SDL_error.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_error.lo -c /home/alessandro/SDL-emscripten/src/SDL_error.c -o build/SDL_error.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_hints.lo -c /home/alessandro/SDL-emscripten/src/SDL_hints.c -o build/SDL_hints.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_hints.lo -c /home/alessandro/SDL-emscripten/src/SDL_hints.c -o build/SDL_hints.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_log.lo -c /home/alessandro/SDL-emscripten/src/SDL_log.c -o build/SDL_log.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_log.lo -c /home/alessandro/SDL-emscripten/src/SDL_log.c -o build/SDL_log.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_atomic.lo -c /home/alessandro/SDL-emscripten/src/atomic/SDL_atomic.c -o build/SDL_atomic.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_atomic.lo -c /home/alessandro/SDL-emscripten/src/atomic/SDL_atomic.c -o build/SDL_atomic.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_spinlock.lo -c /home/alessandro/SDL-emscripten/src/atomic/SDL_spinlock.c -o build/SDL_spinlock.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_spinlock.lo -c /home/alessandro/SDL-emscripten/src/atomic/SDL_spinlock.c -o build/SDL_spinlock.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_audio.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_audio.c -o build/SDL_audio.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_audio.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_audio.c -o build/SDL_audio.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_audiocvt.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_audiocvt.c -o build/SDL_audiocvt.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_audiocvt.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_audiocvt.c -o build/SDL_audiocvt.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_audiodev.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_audiodev.c -o build/SDL_audiodev.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_audiodev.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_audiodev.c -o build/SDL_audiodev.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_audiotypecvt.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_audiotypecvt.c -o build/SDL_audiotypecvt.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_audiotypecvt.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_audiotypecvt.c -o build/SDL_audiotypecvt.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_mixer.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_mixer.c -o build/SDL_mixer.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_mixer.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_mixer.c -o build/SDL_mixer.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_wave.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_wave.c -o build/SDL_wave.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_wave.lo -c /home/alessandro/SDL-emscripten/src/audio/SDL_wave.c -o build/SDL_wave.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_cpuinfo.lo -c /home/alessandro/SDL-emscripten/src/cpuinfo/SDL_cpuinfo.c -o build/SDL_cpuinfo.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_cpuinfo.lo -c /home/alessandro/SDL-emscripten/src/cpuinfo/SDL_cpuinfo.c -o build/SDL_cpuinfo.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_dynapi.lo -c /home/alessandro/SDL-emscripten/src/dynapi/SDL_dynapi.c -o build/SDL_dynapi.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_dynapi.lo -c /home/alessandro/SDL-emscripten/src/dynapi/SDL_dynapi.c -o build/SDL_dynapi.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_clipboardevents.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_clipboardevents.c -o build/SDL_clipboardevents.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_clipboardevents.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_clipboardevents.c -o build/SDL_clipboardevents.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_dropevents.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_dropevents.c -o build/SDL_dropevents.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_dropevents.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_dropevents.c -o build/SDL_dropevents.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_events.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_events.c -o build/SDL_events.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_events.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_events.c -o build/SDL_events.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_gesture.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_gesture.c -o build/SDL_gesture.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_gesture.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_gesture.c -o build/SDL_gesture.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_keyboard.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_keyboard.c -o build/SDL_keyboard.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_keyboard.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_keyboard.c -o build/SDL_keyboard.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_mouse.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_mouse.c -o build/SDL_mouse.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_mouse.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_mouse.c -o build/SDL_mouse.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_quit.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_quit.c -o build/SDL_quit.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_quit.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_quit.c -o build/SDL_quit.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_touch.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_touch.c -o build/SDL_touch.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_touch.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_touch.c -o build/SDL_touch.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_windowevents.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_windowevents.c -o build/SDL_windowevents.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_windowevents.lo -c /home/alessandro/SDL-emscripten/src/events/SDL_windowevents.c -o build/SDL_windowevents.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/bin/bash ./libtool --tag=CC --mode=compile /usr/share/emscripten/emcc -O2  -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include  -fvisibility=hidden -Wall -MMD -MT build/SDL_rwops.lo -c /home/alessandro/SDL-emscripten/src/file/SDL_rwops.c -o build/SDL_rwops.lo
libtool: compile:  /usr/share/emscripten/emcc -O2 -DUSING_GENERATED_CONFIG_H -Iinclude -I/home/alessandro/SDL-emscripten/include -fvisibility=hidden -Wall -MMD -MT build/SDL_rwops.lo -c /home/alessandro/SDL-emscripten/src/file/SDL_rwops.c -o build/SDL_rwops.o
WARNING  root: -I or -L of an absolute path "-I/home/alessandro/SDL-emscripten/include" encountered. If this is to a local system header/library, it may cause problems (local system files make sense for compiling natively on your system, but not necessarily to JavaScript). Pass '-Wno-warn-absolute-paths' to emcc to hide this warning.
/home/alessandro/SDL-emscripten/src/file/SDL_rwops.c:316:9: warning: implicit declaration of
      function 'fseeko64' is invalid in C99 [-Wimplicit-function-declaration]
    if (fseeko64(context->hidden.stdio.fp, (off64_t)offset, whence) == 0) {
        ^
/home/alessandro/SDL-emscripten/src/file/SDL_rwops.c:316:45: error: use of undeclared identifier
      'off64_t'; did you mean '_off64_t'?
    if (fseeko64(context->hidden.stdio.fp, (off64_t)offset, whence) == 0) {
                                            ^
/home/alessandro/SDL-emscripten/src/file/SDL_rwops.c:317:16: warning: implicit declaration of
      function 'ftello64' is invalid in C99 [-Wimplicit-function-declaration]
        return ftello64(context->hidden.stdio.fp);
               ^
2 warnings and 1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
make: **\* [build/SDL_rwops.lo] Error 1

**Comment by gsathya** [comment]
@daft-freak thoughts? has emscripten removed the off64_t symbol?

**Comment by Daft-Freak** [comment]
Hmm.. emscripten's libc does support fseeko64/off64_t. @Norelec91, what does `emcc --version` print?

**Comment by Norelec91** [comment]
@Daft-Freak 
alessandro@alessandro ~/SDL-emscripten $ emcc --version
INFO     root: (Emscripten: Running sanity checks)
emcc (Emscripten GCC-like replacement) 1.5.6 ()
Copyright (C) 2013 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by gsathya** [comment]
@Norelec91 - @juj tells me that emcc 1.5.6 was released a year and a half ago. Can you try updating to the latest emscripten version? The latest emscripten has these symbols defined here:
https://github.com/kripken/emscripten/blob/master/system/include/libc/stdio.h#L187

**Comment by Daft-Freak** [comment]
Also, with the latest emscripten you can use `-s USE_SDL=2` to build and use SDL2 automatically.

**Comment by Norelec91** [comment]
Thanks, I've done to build manually with the latest version of emscripten :)

**Comment by gsathya** [comment]
> Thanks, I've done to build manually with the latest version of emscripten :)

Cool. I'm closing this issue then, feel free to open a new one if something breaks.
