### ISSUE TITLE
Running emconfigure gives a warning, and build fails.

### ISSUE THREAD

**Issue by juj** [gsathya/SDL-emscripten#5]
When I run

   emconfigure ./configure --host=asmjs-unknown-emscripten --disable-sdltest --with-sdl-prefix=~/SDL-emscripten

according to the instructions at https://github.com/gsathya/SDL-emscripten/wiki/Running-the-tests , I get the following warning:

```
configure: WARNING: unrecognized options: --disable-sdltest, --with-sdl-prefix
```

Full log at http://pastebin.com/J96JcGYi . Did I misconfigure something? Running on the master branch should be good?

**Comment by juj** [comment]
Trying to build with emmake make after that fails with http://pastebin.com/8fLkXwQF

**Comment by gsathya** [comment]
https://github.com/gsathya/SDL-emscripten/blob/master/README-emscripten.txt is how you build SDL (/path/to/SDL/).
https://github.com/gsathya/SDL-emscripten/wiki/Running-the-tests is how you build the tests(/path/to/SDL/tests/).  Sorry if that was not clear!

**Comment by juj** [comment]
Oh ok, my bad.

When I try the command line according to README-emscripten.txt, I get this error: http://pastebin.com/9vdm75RZ

Can you reproduce the same issue @gsathya?

**Comment by gsathya** [comment]
Can you try - 
`emconfigure ./configure --host=asmjs-unknown-emscripten --disable-assembly --disable-threads --enable-cpuinfo=false  CFLAGS="-O2"`

This is a mac osx only bug with cpu info. I'll update the README

**Comment by juj** [comment]
Thanks, adding enable-cpuinfo=false works and the build goes through. Updating README for that should fix up the issue.

**Comment by juj** [comment]
I clarified the tests wiki page at https://github.com/gsathya/SDL-emscripten/wiki/Running-the-tests/_compare/604f57324a568d14bb77317c67efa75e35590b1a...793553a34d685f0045f204abdb5c91857115141b to make sure nobody else would do the mistake I did. @gsathya, can you look at that to double-check that the procedure is good now?

**Comment by gsathya** [comment]
> @gsathya, can you look at that to double-check that the procedure is good now?

Looks good. Thanks!
